# Generated by Django 5.0.1 on 2024-03-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poems',
            name='poet_id',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='poets',
        ),
    ]
