# Generated by Django 5.0.1 on 2024-05-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
